### ISSUE TITLE
occasionally rpi101 does not shut down

### ISSUE THREAD

**Issue by danielmcd** [encs-humanoid/structure#1]
When shutting KEN down, sometimes rpi101 (left eye/servos) does not shut down.  It seems that the master is shutting down too quickly and the 'shutdown' message on the /boot topic doesn't get through.

The following messages from the log file ~/.ros/log/boot_2352_1439636319128.log may or may not be relevant.

[rospy.internal][WARNING] 2015-08-16 10:17:55,897: Unknown error initiating TCP/IP socket to 192.168.8.103:34917 (http://192.168.8.103:41812/): Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 519, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-08-16 10:22:03,553: topic[/boot] adding connection to [unknown], count 2
[rospy.internal][ERROR] 2015-08-16 10:22:03,571: Unable to initiate TCP/IP socket to 192.168.8.100:43947 (http://192.168.8.100:49088/): Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 521, in connect
    self.read_header()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 587, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 551, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2015-08-16 10:22:03,575: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.core][INFO] 2015-08-16 10:25:01,957: signal_shutdown [signal-15]
[rospy.registration][WARNING] 2015-08-16 10:25:04,729: unclean shutdown

**Comment by danielmcd** [comment]
I finally figured out that this was a problem when using the "Initiate shutdown sequence" verbal command.  This was implemented with rostopic pub, which latches (waits for subscribers) for 3 seconds.  This was apparently not enough time for the RPI's to get the message.  I changed this to publish every second until with -r 1 on the rostopic pub command line, and it seems to be working.  I also made poweroff timing in boot_node.py configurable and set sonny to delay 15 seconds.  This should allow the RPI's to finish their business before roscore disappears.
